name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *"  # Her gün saat 00:00'da çalışır (UTC)
  push:
    branches:
      - main
  workflow_dispatch:  # Elle tetikleme için

jobs:
  generate:
    runs-on: ubuntu-latest
    name: generate snake.svg
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v3

      - name: Generate the snake animation
        uses: Platane/snk@v3
        with:
          github_user_name: alirizakaygusuz
          outputs: |
            ./output/github-contribution-grid-snake.svg

      - name: Push the generated snake.svg
        uses: EndBug/add-and-commit@v9
        with:
          message: "Generate contribution snake"
          add: "output/github-contribution-grid-snake.svg"
